[package]
name = "microservice_fuhrparkverwaltung"
version = "0.0.1"
authors = ["thoeff2s"]
edition = "2018"

[[bin]]
name = "restapi"
path = "./src/main.rs"

[dependencies]
rocket = "0.4.11"
postgres = "0.19.4"
itertools = "0.10.5"
serde_json = "1.0.85"
serde = "1.0.145"