[package]
name = "microservice_fuhrparkverwaltung"
version = "0.0.1"
authors = ["thoeff2s"]
edition = "2018"

[[bin]]
name = "restapi"
path = "./src/main.rs"

[dependencies]
nickel = "*"
postgres = "0.19.4"
itertools = "0.10.5"